repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    - id: isort
      args:
        - --multi-line=3
        - --trailing-comma
        - --force-grid-wrap=0
        - --combine-as
        - --line-width 88
