dist: xenial
language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"

addons:
    postgresql: "9.5"

services:
  - postgresql

install:
    - pip install -U -r requirements.txt
    - pip install -U -r requirements_dev.txt

script:
    - scripts/test

after_script:
    - pip install codecov
    - codecov
