version: '3.7'
services:
  qllr:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "127.0.0.1:7081:8000"
    environment:
      HOST: 0.0.0.0
      PORT: 8000
    env_file:
      - .env
    depends_on: ["db"]

  db:
    image: "postgres:9.5"
    environment:
      POSTGRES_USER: eugene
      POSTGRES_PASSWORD: bebebe
      POSTGRES_DB: qllr
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  dev:
    build:
      context: .
      dockerfile: Dockerfile.develop.buster
    volumes:
      - .:/opt/qllr
    ports:
      - "127.0.0.1:7081:8000"
