FROM python:3.6-stretch AS production

WORKDIR /opt/qllr

COPY --chown=www-data . .

RUN python3 -m pip install -r requirements.txt

USER www-data

CMD ["sh", "-c", "./docker/entrypoint.py && ./main.py"]
