#!/bin/sh -e

export PREFIX=""
export TARGET="qllr tests"

if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

#${PREFIX}autoflake --in-place --recursive $TARGET
${PREFIX}black $TARGET
${PREFIX}isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --combine-as --line-width 88 --recursive --apply $TARGET
#${PREFIX}mypy $TARGET --ignore-missing-imports --disallow-untyped-defs
