#!/bin/sh -e

export TARGET="qllr tests contrib main.py"

set -x

PYTHONPATH=. python -m pytest -o cache_dir=/tmp/.qllr_test_cache --cov=qllr --cov=tests --ignore venv -W ignore::DeprecationWarning ${@}
${PREFIX}black $TARGET --check
