name: Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8", "3.7"]
        os: ["ubuntu-22.04"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install postgresql
        uses: tj-actions/install-postgresql@v3
        with:
          postgresql-version: 12
      - uses: actions/checkout@v3
      - name: Include ppa repository
        run: sudo add-apt-repository ppa:deadsnakes/ppa
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          sudo apt-get install python${{ matrix.python-version }}-dev python${{ matrix.python-version }}-distutils
          sudo update-alternatives --install /usr/bin/python3 python3 `which python${{ matrix.python-version }}` 1
          sudo update-alternatives --install /usr/bin/python3-config python3-config `which python${{ matrix.python-version }}-config` 1
      - name: Upgrade setuptools for Python 3.12
        if: matrix.python-version == '3.12'
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py "setuptools > 69.0"
      - name: Install requirements
        run: python3 -m pip install -r requirements.txt
      - name: Install development requirements
        run: python3 -m pip install -r requirements_dev.txt
      - name: Install pg_tmp
        run: |
          sudo apt-get install build-essential
          git clone https://github.com/eradman/ephemeralpg.git
          cd ephemeralpg && make && sudo make install
      - name: Test
        run: ./scripts/test
      - uses: codecov/codecov-action@v1
