name: Docker

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    strategy:
      matrix:
        dockerfile-suffix: [
        "alt10", "sisyphus",
        "buster", "bullseye", "bookworm", "trixie",
        "focal", "jammy", "noble"
        ]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.develop.${{ matrix.dockerfile-suffix }}
          push: false
          load: true
          tags: test:latest
      - name: Test
        run: docker run --rm test:latest
